# Public Settings
#
# IMPORTANT: DON'T INCLUDE SENSITIVE SETTINGS IN THIS FILE!
#
# These are settings that are shared across all environments and are
# safe to include in version control.
#
# Environment-specific settings should be added to a non-versioned
# settings.<env>.toml file (e.g. settings.production.toml).

[djangokit]
package = "colors"
title = "Colors"
description = "Colors"
global_stylesheets = ["bootstrap.css", "global.css"]
ssr = false
